create table employee (
    id int8 generated by default as identity,
    date_of_birth date not null,
    department_id int8 not null,
    first_name varchar(128) not null,
    gender int4 not null,
    job_title varchar(128) not null,
    last_name varchar(128) not null,
    primary key (id)
)